//
//  EnStrings.kt
//  由 iOS Localizable.xcstrings 生成的英文对照表（key = 中文源文案，与 iOS 完全同源）。
//  重新生成：见 android 仓库 README。请勿手改——改 iOS xcstrings 后重新生成。
//

package com.feiyu.majiang.core

val EN_STRINGS: Map<String, String> = mapOf(
    "%lld / %lld" to "%1\$lld / %2\$lld",
    "%lld / 4 组" to "%lld / 4 sets",
    "%lld 分" to "%lld pts",
    "%lld 分（含花 %lld）" to "%1\$lld pts (incl. %2\$lld flower)",
    "%lld 番" to "%lld fan",
    "%lld 番·封顶 %lld" to "%lld fan · cap %lld",
    "%lld 种" to "%lld options",
    "+%lld 底" to "+%lld base",
    "+%lld 番" to "+%lld fan",
    "+1 底" to "+1 base",
    "+1 番" to "+1 fan",
    "+4 番" to "+4 fan",
    "0 番" to "0 fan",
    "1" to "1",
    "1 番" to "1 fan",
    "123、456、789 分属三种花色。" to "123, 456 and 789, one in each suit.",
    "2 番" to "2 fan",
    "3 番" to "3 fan",
    "3 番（8 倍）" to "3 fan (8×)",
    "4 张同牌：杠 / 手握 4 张 / 碰 + 手里第 4 张" to "Four identical tiles: a kong, four in hand, or a pong + the 4th in hand",
    "4 番" to "4 fan",
    "4 番（16 倍）" to "4 fan (16×)",
    "5 番" to "5 fan",
    "5 番（32 倍）" to "5 fan (32×)",
    "AI 正在识别牌面…" to "Recognizing tiles…",
    "「%@」只有一张。" to "There is only one 「%@」.",
    "「%@」在手牌和副露里已用满 4 张。" to "All 4 of 「%@」are already used across hand and melds.",
    "「%@」总数会超过 4 张，无法%@。" to "That would exceed 4 of 「%@」— can't %@.",
    "一、九或风牌的刻子（箭刻另计），每个 1 分。" to "A pung of terminals or winds (dragon pungs score separately) — 1 point each.",
    "一种数牌花色 + 字牌。" to "One suit plus honours.",
    "一般高" to "Pure Double Chow",
    "一色三同顺" to "Pure Triple Chow",
    "一色三步高" to "Pure Shifted Chows",
    "一色三节高" to "Pure Shifted Pungs",
    "一色双龙会" to "Pure Terminal Chows",
    "一色四同顺" to "Quadruple Chow",
    "一色四步高" to "Four Pure Shifted Chows",
    "一色四节高" to "Four Pure Shifted Pungs",
    "七个对子。" to "Seven pairs.",
    "七对" to "Seven Pairs",
    "七对里四张相同当两对" to "Four identical tiles count as two pairs",
    "七小对" to "Seven Pairs",
    "七小对且全是 2/5/8" to "Seven Pairs, all 2/5/8",
    "七小对里有 1 个「龙」（4 张相同），每多一龙再 +1 番。" to "A seven-pairs hand with one dragon (4 identical tiles); +1 fan per extra dragon.",
    "七小对里有 2 个「龙」（各 4 张相同）。" to "A seven-pairs hand with two dragons (4 identical tiles each).",
    "七小对里有 3 个「龙」（各 4 张相同）。" to "A seven-pairs hand with three dragons (4 identical tiles each).",
    "七小对（2 番）" to "Seven Pairs (2 fan)",
    "七小对，且所有牌都是 2 / 5 / 8。" to "Seven Pairs where every tile is a 2, 5, or 8.",
    "七星不靠" to "Greater Honours and Knitted Tiles",
    "七种字牌齐全的全不靠。" to "Lesser Honours and Knitted Tiles with all seven honours present.",
    "万、筒、条、风、箭五门都有。" to "Characters, dots, bamboo, winds and dragons all present.",
    "万、筒、条里缺了一门。" to "One of the three suits is missing entirely.",
    "三个暗刻。" to "Three concealed pungs.",
    "三个杠。" to "Three kongs.",
    "三个风刻 + 第四种风作将。" to "Three wind pungs plus a pair of the fourth wind.",
    "三个风刻。" to "Three wind pungs.",
    "三同刻" to "Triple Pung",
    "三暗刻" to "Three Concealed Pungs",
    "三杠" to "Three Kongs",
    "三杠之外每个杠另算" to "Score each kong on top of Three Kongs",
    "三种花色依次加一的刻子。" to "Three pungs with consecutive ranks, one in each suit.",
    "三种花色同一点数的刻子。" to "The same-numbered pung in all three suits.",
    "三种花色同一起点的顺子。" to "The same-numbered chow in all three suits.",
    "三种花色的顺子，起点依次加一。" to "Three chows, one in each suit, whose starts rise by 1 each time.",
    "三色三同顺" to "Mixed Triple Chow",
    "三色三步高" to "Mixed Shifted Chows",
    "三色三节高" to "Mixed Shifted Pungs",
    "三色双龙会" to "Three-Suited Terminal Chows",
    "三豪华七小对" to "Triple Deluxe Seven Pairs",
    "三门数牌分别是 147、258、369，共九张。" to "147, 258 and 369, one pattern per suit — nine tiles.",
    "三风刻" to "Big Three Winds",
    "下面这几条是各地规则书写法有分歧的地方，按你们桌上的打法选。默认是最常见的算法。" to "Rulebooks disagree on the points below, so pick whatever your table plays. The defaults follow the most common reading.",
    "不划区域也能识别，但整桌入镜时牌小、易混入别人的牌，准确率会下降；建议先圈出自己的手牌。" to "Recognition works without drawing a box too, but a whole-table shot makes tiles small and easy to mix up with other players' — circling your own tiles first is recommended.",
    "不够起和" to "under 8 pts",
    "不封顶" to "No cap",
    "不求人" to "Fully Concealed Hand",
    "不计" to "Not counted",
    "与本圈风相同的风刻。" to "A pung of the prevalent wind.",
    "与自己门风（座位风）相同的风刻。" to "A pung of your own seat wind.",
    "东" to "East",
    "东南西北四个风刻（或杠）。" to "Pungs (or kongs) of all four winds.",
    "两个明杠。" to "Two exposed kongs.",
    "两个暗刻。" to "Two concealed pungs.",
    "两个暗杠。" to "Two concealed kongs.",
    "两个箭刻 + 第三种箭牌作将。" to "Two dragon pungs plus a pair of the third dragon.",
    "两个箭刻。" to "Two dragon pungs.",
    "两种花色同一点数的刻子。" to "The same-numbered pung in two different suits.",
    "两种花色同一起点的顺子。" to "The same-numbered chow in two different suits.",
    "两门各 123 + 789，第三门的 5 作将。" to "123 and 789 in two suits, with a pair of 5s in the third.",
    "中、发、白任一的刻子（或杠），每个 2 分。" to "A pung (or kong) of red, green or white dragon — 2 points each.",
    "中发白三个箭刻（或杠）。" to "Pungs (or kongs) of red, green and white dragons.",
    "九莲宝灯" to "Nine Gates",
    "九莲宝灯同时计双暗刻" to "Nine Gates also scores Two Concealed Pungs",
    "五门齐" to "All Types",
    "从相册选择识别手牌" to "Choose Photo to Recognize",
    "会自动框出你的牌" to "Your tiles are framed for you",
    "元" to "unit",
    "兜底" to "fallback",
    "全不靠" to "Lesser Honours and Knitted Tiles",
    "全中" to "Middle Tiles",
    "全双刻" to "All Even Pungs",
    "全大" to "Upper Tiles",
    "全小" to "Lower Tiles",
    "全带五" to "All Fives",
    "全带幺" to "Outside Hand",
    "全求人" to "Melded Hand",
    "全部由 2/3/4/6/8 条和发组成。" to "Only 2/3/4/6/8 bamboo and the green dragon.",
    "全部由 2/4/6/8 的刻子和将组成。" to "Only pungs and a pair of 2s, 4s, 6s and 8s.",
    "全部由一、九的刻子和将组成，不含字牌。" to "Only pungs and a pair of 1s and 9s, no honours.",
    "全部由幺九牌和字牌的刻子与将组成。" to "Every set and the pair is made of terminals or honours, all pungs.",
    "共 %lld 门" to "%lld waits",
    "关闭" to "Off",
    "再选 1 张" to "Select 1 more",
    "凑齐 4 张同牌：杠 / 手握 4 张 / 碰 + 手里第 4 张" to "Four identical tiles: a kong, four in hand, or a pong + the 4th in hand",
    "凑齐 4 张相同的牌（杠 / 手握 4 张 / 碰 + 第 4 张）。" to "Four identical tiles (a kong, four in hand, or a pong + the 4th tile).",
    "分数按点炮和计；自摸、场景番另加。国标起和 8 分。" to "Points are for a win by discard; self-draw and situational fan add more. MCR needs 8 points to win.",
    "分析手牌" to "Analyze",
    "分析结果" to "Result",
    "切换语言" to "Switch language",
    "删除 %@%@" to "Remove %@%@",
    "别家开杠后打出的牌被你胡。" to "You win on a tile discarded by another player right after they declared a kong.",
    "别家补杠的那张牌正是你要胡的，抢过来胡。" to "You win by robbing the tile another player used to add to a kong.",
    "剩%lld" to "%lld left",
    "加入到" to "Add to",
    "加底（+1 底分）" to "Add base (+1 base)",
    "加番（+1 番）" to "Add fan (+1 fan)",
    "北" to "North",
    "十三幺" to "Thirteen Orphans",
    "十三种幺九牌各一张，其中任一张成对。" to "One of each of the thirteen terminals and honours, with any one of them paired.",
    "十八罗汉" to "Eighteen Arhats",
    "十四张互不成套：三门数牌分别取 147/258/369，其余为字牌。" to "Fourteen unrelated tiles: each suit takes one of 147 / 258 / 369, the rest are honours.",
    "单钓将" to "Single Wait",
    "南" to "South",
    "双同刻" to "Double Pung",
    "双明杠" to "Two Melded Kongs",
    "双暗刻" to "Two Concealed Pungs",
    "双暗杠" to "Two Concealed Kongs",
    "双箭刻" to "Two Dragon Pungs",
    "双豪华七小对" to "Double Deluxe Seven Pairs",
    "取消" to "Cancel",
    "只有杠才算根" to "Only kongs count as root",
    "只有杠：明杠 / 暗杠" to "Kongs only: exposed / concealed kong",
    "只有花牌——请再选入参与和牌的牌。" to "Flowers only — add the tiles that actually form your hand.",
    "只用万/筒/条，必须缺一门，无吃；按番数翻倍算钱。" to "Characters/dots/bamboo only, one suit must be missing, no chow; money doubles per fan.",
    "可算向听 / 听牌" to "Shanten / tenpai ready",
    "可给打牌建议" to "Discard suggestions ready",
    "吃" to "Chow",
    "吃只能用数牌，且要从 1–7 起头凑连续三张。" to "A chow must be a suited run starting from 1–7.",
    "吃：点起始牌，自动配成连续三张（如点「3万」= 吃 345 万）。分析工具不限制只能吃上家。" to "Chow: tap the lowest tile and the run is completed for you (tap 3 characters = chow 3-4-5 characters). This tool does not restrict who you claimed it from.",
    "同一花色 123 123 789 789 + 55 作将。" to "In one suit: 123 123 789 789 with a pair of 5s.",
    "同一花色七个连号的对子。" to "Seven pairs of consecutive ranks in one suit.",
    "同一花色三个依次加一的刻子。" to "Three pungs in one suit with consecutive ranks.",
    "同一花色三副相同的顺子。" to "Three identical chows in one suit.",
    "同一花色三副顺子，起点依次加一或加二。" to "Three chows in one suit whose starts rise by 1 or by 2 each time.",
    "同一花色两副相同的顺子。" to "Two identical chows in one suit.",
    "同一花色两副相连的顺子，如 123 + 456。" to "Two chows in one suit that run on, such as 123 + 456.",
    "同一花色四个依次加一的刻子。" to "Four pungs in one suit with consecutive ranks.",
    "同一花色四副相同的顺子。" to "Four identical chows in one suit.",
    "同一花色四副顺子，起点依次加一或加二。" to "Four chows in one suit whose starts rise by 1 or by 2 each time.",
    "同一花色的 123 + 789。" to "123 and 789 in the same suit.",
    "同一花色的 123 456 789。" to "123, 456 and 789 all in one suit.",
    "向听 %lld" to "%lld away",
    "含风/箭/花，可吃，81 种番型，起和 8 分。" to "Winds, dragons and flowers; chow allowed; 81 fan types; 8-point minimum.",
    "听牌" to "Tenpai",
    "听牌计算器" to "Tenpai Calculator",
    "听牌计算器 · 国标" to "Tenpai Calculator · MCR",
    "听牌（空听）" to "Tenpai (Dead Wait)",
    "和 123 里的 3 或 789 里的 7。" to "Winning on the 3 of 123 or the 7 of 789.",
    "和「%@」" to "Winning on 「%@」",
    "和出九莲宝灯时：开 = 牌里那两个暗刻另加 2 分；关 = 只算九莲宝灯的 88 分。" to "When you win with Nine Gates — On: the two concealed pungs inside it add 2 more points. Off: Nine Gates alone, 88 points.",
    "和别家打出的最后一张牌。" to "Winning on the last discard of the hand.",
    "和牌时除自摸、花牌外没有任何番种，计 8 分。" to "A winning hand with no fan at all apart from self-draw and flowers — worth 8 points.",
    "和的这张牌是明面上已见三张后的最后一张。" to "The winning tile is the fourth and last one, the other three already visible.",
    "和的那张牌凑成将。" to "The winning tile completes the pair.",
    "和的那张牌能有好几种读法时：开 = 按对你有利的那种读，这 1 分照给；关 = 只有读法唯一、没有第二种拆法时才给这 1 分。" to "When the winning tile can be read more than one way — On: use the reading that favors you and score the 1 point. Off: score it only when there is exactly one way to read the wait.",
    "和绝张" to "Last Tile",
    "和顺子中间那张。" to "Winning on the middle tile of a chow.",
    "喜相逢" to "Mixed Double Chow",
    "四个暗刻（暗杠算暗刻）。点炮成的刻子算明刻。" to "Four concealed pungs (a concealed kong counts). A pung completed by a discard counts as melded.",
    "四个杠（明暗不限）。" to "Four kongs, exposed or concealed.",
    "四副都已碰 / 杠，手里只剩一对单钓将；已含碰碰胡。" to "All four melds are ponged/konged, leaving only a single pair waiting; includes All Pungs.",
    "四副面子全是刻子（碰 / 杠），没有顺子。" to "All four melds are triplets (pong/kong), with no sequences.",
    "四副面子全是吃碰明杠得来的，最后单钓别家打出的牌。" to "All four sets claimed from others, winning on a discard that pairs your last tile.",
    "四副面子都是刻子或杠。" to "All four sets are pungs or kongs.",
    "四副顺子 + 数牌作将。" to "Four chows with a suited pair.",
    "四川麻将（血战到底）" to "Sichuan (Bloody Battle)",
    "四张相同的牌，三张在一副面子里、另一张在别处，每组 2 分。" to "All four copies of a tile, three in one set and the fourth elsewhere — 2 points each.",
    "四归一" to "Tile Hog",
    "四暗刻" to "Four Concealed Pungs",
    "四杠" to "Four Kongs",
    "国标不按底分翻倍算钱，只算番分，起和 8 分。花牌每张 1 分，不计入起和分。拍照识别只认万/筒/条，风牌、箭牌、花牌需手动补入。" to "MCR scores points rather than doubling a base stake; you need 8 points to win. Each flower is worth 1 point but does not count toward the 8. Photo recognition only reads characters/dots/bamboo — winds, dragons and flowers must be added by hand.",
    "国标模式：拍照只能识别万/筒/条，风牌、箭牌、花牌认不出来，请在键盘上手动补入。" to "MCR: photo recognition only reads characters/dots/bamboo. Winds, dragons and flowers are not recognised — add them with the keypad.",
    "国标起和 8 分：一副牌的番分（不含花牌）达到 8 分才能和。番型之间遵守不重复计算原则——已经被高番型「包含」的低番型不再另计。" to "MCR needs 8 points to win, flowers excluded. Fan types follow the non-repeat principle: a lower fan already implied by a higher one is not counted again.",
    "国标起和 8 分：橙色的听牌即使和了也不够起和。点牌可看番型明细。" to "MCR needs 8 points to win — waits shown in orange would not reach it. Tap a tile for the fan breakdown.",
    "国标起和 8 分；花牌每张 1 分但不计入起和分。" to "MCR needs 8 points to win. Each flower scores 1 point but does not count toward the 8.",
    "国标起和 8 分；花牌每张 1 分但不计入起和分。番型明细按「点炮和」列出。" to "MCR needs 8 points to win. Each flower scores 1 point but does not count toward the 8. The breakdown below is for a win by discard.",
    "国标麻将" to "Chinese Official (MCR)",
    "圈出自己的手牌" to "Circle your own tiles",
    "圈出自己的手牌（含碰/杠），排除别人的牌和弃牌堆，识别更准" to "Circle just your own tiles (including pongs/kongs) — excluding other players' tiles and the discard pile improves accuracy",
    "圈风" to "Prevalent wind",
    "圈风 / 门风" to "Prevalent / seat wind",
    "圈风刻" to "Prevalent Wind",
    "在底部选择花色与点数加入；点击已选牌可删除" to "Add tiles from the keyboard below; tap a tile to remove it",
    "在照片上按住并拖动，画一个框只圈住你自己的手牌（含碰/杠），排除别人的牌和弃牌堆，识别会更准。" to "Press and drag on the photo to draw a box around just your own tiles (including pongs/kongs). Excluding other players' tiles and the discard pile improves accuracy.",
    "地胡" to "Earthly Hand",
    "场景番（胡牌时勾选）" to "Situational Fans (check at win)",
    "坎张" to "Closed Wait",
    "基础牌型（自动识别，可叠加）" to "Base Patterns (auto-detected, stackable)",
    "大三元" to "Big Three Dragons",
    "大于五" to "Upper Four",
    "大四喜" to "Big Four Winds",
    "天胡" to "Heavenly Hand",
    "妙手回春" to "Last Tile Draw",
    "字一色" to "All Honours",
    "字一色同时计混幺九" to "All Honors also scores All Terminals and Honors",
    "完成" to "Done",
    "封顶" to "Cap",
    "将七对" to "Jiang Seven Pairs",
    "将对" to "Jiang Pungs",
    "将对 / 将七对（3 / 4 番）" to "Jiang Pungs / Jiang Seven Pairs (3 / 4 fan)",
    "小三元" to "Little Three Dragons",
    "小于五" to "Lower Four",
    "小四喜" to "Little Four Winds",
    "尚未选牌" to "No tiles yet",
    "已关闭" to "Off",
    "已吃、已碰、已杠的牌放这里：底部切到「吃 / 碰 / 明杠 / 暗杠」后点牌加入。吃只能吃上家，但本工具不强制这一条——请自行确认这副吃是合法的。" to "Put your chows, pongs and kongs here: switch the keypad to Chow / Pong / Exposed kong / Concealed kong and tap a tile. A chow may only be claimed from the player to your left — this tool does not enforce that, so make sure the chow is legal.",
    "已含碰碰胡，不叠加" to "Includes All Pungs; not stacked",
    "已听牌，但可胡的牌都已在手中（4 张用尽），无法再胡——空听。" to "You're ready, but every winning tile is already in your hand (all 4 used) — a dead wait, no win possible.",
    "已和！" to "Won!",
    "已碰、已杠的牌放这里：底部切到「碰 / 明杠 / 暗杠」后点牌加入。" to "Melded (ponged/konged) tiles go here: switch the bottom keyboard to Pong / Exposed Kong / Concealed Kong, then tap a tile.",
    "已自动分组：%lld 副露（含暗杠——只露一张、靠猜，建议核对「桌上的牌」）。" to "Auto-grouped: %lld melds, including a concealed kong guessed from a single exposed tile. Please check Table Tiles.",
    "已自动分组：%lld 副露，建议核对「桌上的牌」。" to "Auto-grouped: %lld melds. Please check Table Tiles.",
    "已自动分组：%lld 张手牌 + %lld 副露%@。请核对「桌上的牌」无误后，点『分析手牌』。" to "Auto-grouped: %lld hand tiles + %lld melds%@. Check the Table Tiles, then tap Analyze.",
    "已自动框出你的牌，框不准可拖四角或四边调整" to "Your tiles are framed — drag a corner or an edge if it's off",
    "已识别 %lld 张，张数不构成可分析手牌，请核对后再分析。" to "Recognized %lld tiles — not a hand that can be analyzed. Please check them, then analyze.",
    "已识别 %lld 张，请核对后再分析。" to "Recognized %lld tiles; please double-check before analyzing.",
    "常见组合（自动叠出，不单列）" to "Common Combos (auto-stacked, not listed separately)",
    "平和" to "All Chows",
    "平胡" to "Basic Win",
    "幺九刻" to "Pung of Terminals or Honours",
    "庄家起手胡" to "Dealer wins on the opening hand",
    "庄家起手（发完牌）即胡。" to "The dealer wins immediately on the opening hand.",
    "底分" to "Base stake",
    "开了三个杠时：开 = 三杠 32 分之外，每个明杠再加 1 分、暗杠再加 2 分；关 = 只算三杠的 32 分。" to "When you have three kongs — On: 32 points for Three Kongs plus 1 point per melded kong and 2 per concealed kong. Off: just the 32 points.",
    "开杠后补摸到的那张牌自摸胡。" to "You self-draw and win on the replacement tile drawn after declaring a kong.",
    "开杠后补摸的那张牌自摸和牌。" to "Winning on the replacement tile drawn after a kong.",
    "当前副露 %lld 组，手牌需为 %@ 张（听牌）或再多 1 张（打牌建议）。当前手牌 %lld 张。" to "With %lld melds, the hand needs %@ tiles (tenpai) or one more (discard advice). Currently %lld tiles.",
    "影响圈风刻、门风刻（各 2 分）。门风就是自己的座位风。" to "Affects Prevalent Wind and Seat Wind (2 points each). Your seat wind is the wind of your seat.",
    "恢复默认规则" to "Restore Default Rules",
    "手牌" to "Hand",
    "手牌与副露合计含万、筒、条三门花色（花猪）。四川麻将需缺一门，请打缺其中一门。" to "Hand and melds together use all three suits — Characters, Dots, and Bamboo (a \"flower pig\"). Sichuan mahjong requires dropping one suit.",
    "手牌加副露不满 13 张，缺的面子按「能凑成」处理，所以这里只列听牌不算番分。" to "Hand plus melds is short of 13 tiles — the missing sets are assumed completable, so waits are listed without points.",
    "手牌加副露不满 14 张，缺的面子按「能凑成」处理，所以只排向听/进张，不算番分。" to "Hand plus melds is short of 14 tiles — the missing sets are assumed completable, so discards are ranked by shanten and draws only, without points.",
    "手牌太多，放不下这组副露——先删几张手牌（碰/杠会占掉 3 张名额）。" to "Too many hand tiles to add this meld — remove some first (a pong/kong takes 3 slots).",
    "手里有四张一样的牌时：开 = 拆成两对，照样算七对；关 = 不算七对，能拆成顺子刻子就按普通牌型算，拆不出来就是没和。" to "When you hold four of the same tile — On: split them into two pairs and still score Seven Pairs. Off: no Seven Pairs; the hand is read as a normal hand if it can be, and is not a win if it cannot.",
    "手里的牌" to "Hand Tiles",
    "打" to "Discard",
    "打牌建议" to "Discard Suggestions",
    "抢别家补杠的那张牌和牌。" to "Winning on the tile another player adds to a melded pung.",
    "抢杠和" to "Robbing the Kong",
    "抢杠胡" to "Robbing the Kong",
    "拍完会自动框住你自己的牌（含碰/杠），排除别人的牌和弃牌堆。框得不准就拖四角或四边调整，或在照片上重新拖一个框。" to "After the shot, your own tiles (including pongs and kongs) are framed automatically, leaving out other players' tiles and the discard pile. If the frame is off, drag a corner or an edge — or drag a new one anywhere on the photo.",
    "拍照" to "Take Photo",
    "拍照识别在主界面底部；这里是从相册里选一张已有的照片来识别。" to "Photo recognition is at the bottom of the main screen; this picks an existing photo from your library instead.",
    "拍照识别手牌" to "Recognize from Photo",
    "换一张" to "Change",
    "推不倒" to "Reversible Tiles",
    "提示" to "Notice",
    "摸走最后一张牌自摸胡。" to "You self-draw and win on the very last tile of the wall.",
    "撤销" to "Undo",
    "整副牌不含幺九牌和字牌。" to "No terminals and no honours anywhere.",
    "整副牌全是风牌和箭牌。" to "The whole hand is winds and dragons.",
    "整副牌全是风牌箭牌时：开 = 字一色之外再加 32 分的混幺九；关 = 只算字一色的 64 分。" to "When every tile is a wind or dragon — On: All Honors plus another 32 points for All Terminals and Honors. Off: All Honors alone, 64 points.",
    "整副牌只有 1、2、3、4。" to "Only 1s, 2s, 3s and 4s.",
    "整副牌只有 1、2、3。" to "Only 1s, 2s and 3s.",
    "整副牌只有 4、5、6。" to "Only 4s, 5s and 6s.",
    "整副牌只有 6、7、8、9。" to "Only 6s, 7s, 8s and 9s.",
    "整副牌只有 7、8、9。" to "Only 7s, 8s and 9s.",
    "整副牌只用一种数牌花色，不含字牌。" to "One suit only, no honours.",
    "整副牌只用一种花色（全万 / 全筒 / 全条）。" to "The whole hand uses a single suit (all Characters / Dots / Bamboo).",
    "整副牌完全没有 1 和 9" to "No 1s or 9s anywhere in the hand",
    "整副牌完全没有 1 和 9。" to "The whole hand contains no 1s or 9s.",
    "整副牌没有字牌。" to "No honour tiles at all.",
    "整副牌都是上下对称的牌：1234589 筒、245689 条、白。" to "Only tiles that look the same upside down: 1234589 dots, 245689 bamboo and the white dragon.",
    "断幺" to "All Simples",
    "断幺九" to "All Simples",
    "断幺九（+1 番）" to "All Simples (+1 fan)",
    "旋转" to "Rotate",
    "无字" to "No Honours",
    "无有效进张。" to "No useful draws.",
    "无有效进张（受缺一门所限）。" to "No useful draws (limited by the missing-suit rule).",
    "无法读取所选图片，请换一张试试。" to "Could not read the image; please try another.",
    "无番和" to "Chicken Hand",
    "明杠" to "Exposed Kong",
    "明杠，每个 1 分。" to "An exposed kong — 1 point each.",
    "普通牌型，没有特殊番型，0 番。" to "An ordinary winning hand with no special fan — 0 fan.",
    "暗杠" to "Concealed Kong",
    "暗杠，每个 2 分。" to "A concealed kong — 2 points each.",
    "最多 4 组副露。" to "At most 4 melds.",
    "最高 %lld 分" to "best %lld pts",
    "最高 %lld 番" to "Up to %lld fan",
    "未找到本地识别模型文件。" to "On-device recognition model not found.",
    "未能从图片中识别到麻将牌，请确保牌面清晰、正对镜头、光线充足。" to "No tiles recognized. Make sure the tiles are clear, facing the camera, and well lit.",
    "本地识别失败：%@" to "On-device recognition failed: %@",
    "杠上开花" to "After-Kong Bloom",
    "杠上开花（+1 番）" to "After-Kong Bloom (+1 fan)",
    "杠上炮" to "After-Kong Discard",
    "根" to "Root",
    "根 = 4 张同牌。默认「碰 + 手里第 4 张」「手握 4 张」也算根；开启「只有杠才算根」后仅明杠/暗杠算。加底/关闭时，杠只按刮风下雨即时结算，不再翻倍进胡牌金额。" to "Root = four identical tiles. By default a pong + 4th tile and four-in-hand also count; turn on “Only kongs count as root” to count exposed/concealed kongs only. On Add-base/Off, kongs settle instantly (wind/rain) and no longer double the win amount.",
    "根 = 凑齐 4 张同牌（杠 / 手握 4 张 / 碰 + 第 4 张）。加底/关闭时，杠只按刮风下雨即时结算，不再翻倍进胡牌金额。" to "Root = four identical tiles (a kong, four in hand, or a pong + 4th tile). On Add-base/Off, kongs settle instantly (wind/rain) and no longer double the win amount.",
    "框选自己的手牌 · 可旋转" to "Circle your tiles · rotatable",
    "桌上的牌（吃 / 碰 / 杠）" to "On the table (chow / pong / kong)",
    "桌上的牌（碰 / 杠）" to "Table Tiles (Pong / Kong)",
    "正在自动框选你的牌…" to "Framing your tiles…",
    "每个 +1 底" to "+1 base each",
    "每个 +1 番" to "+1 fan each",
    "每副面子和将都含有 5。" to "Every set and the pair contains a 5.",
    "每副面子和将都含有幺九牌或字牌。" to "Every set and the pair contains a terminal or an honour.",
    "每多一龙再 +1：双豪华 4 番、三豪华 5 番" to "+1 per extra dragon: Double Deluxe 4 fan, Triple Deluxe 5 fan",
    "每张花牌 1 分，不计入起和的 8 分。" to "Each flower scores 1 point and does not count toward the 8-point minimum.",
    "没有吃碰明杠，且和别家打出的牌。" to "No chow, pong or exposed kong, winning on someone else's discard.",
    "没有碰、没有明杠（暗杠可以），点炮或自摸都算。" to "No pong and no exposed kong (concealed kong is OK); counts on discard or self-draw.",
    "没有碰、没有明杠（暗杠可），点炮/自摸都算" to "No pong, no exposed kong (concealed kong OK); counts on discard and self-draw",
    "海底捞月" to "Last-Tile Draw",
    "海底捞月（和最后一张打出的牌）" to "Last Tile Claim",
    "混一色" to "Half Flush",
    "混幺九" to "All Terminals and Honours",
    "清一色" to "Pure Suit",
    "清一色（2 番）" to "Pure Suit (2 fan)",
    "清七对" to "Pure Seven Pairs",
    "清对（清一色 + 碰碰胡）" to "Pure Pungs (Pure Suit + All Pungs)",
    "清幺九" to "All Terminals",
    "清空全部" to "Clear all",
    "清豪七" to "Pure Deluxe Seven Pairs",
    "清金钩钓" to "Pure Golden Hook",
    "清除框选" to "Clear selection",
    "清龙" to "Pure Straight",
    "点炮" to "Discard",
    "点炮 · 放炮者付" to "Discard · discarder pays",
    "点炮侧" to "discard side",
    "点炮和" to "By discard",
    "点炮时" to "On discard:",
    "点炮（放炮者付）" to "Discard (discarder pays)",
    "点番型看含义" to "Tap a fan to see what it means",
    "点选加入" to "Tap to add",
    "牌型成立" to "Shape is valid",
    "玩法" to "Game",
    "由 7 个对子组成（非标准面子牌型）。" to "Made of seven pairs (not the standard melds-and-pair shape).",
    "番分" to "Points",
    "番型" to "Fans",
    "番型一览" to "Fan Reference",
    "番型一览（81 种）" to "Fan reference (81 types)",
    "番型开关" to "Fan Toggles",
    "番型明细" to "Fan Breakdown",
    "番型（按点炮和）" to "Fan (win by discard)",
    "番数与金额按点炮胡、当前规则计；自摸另加。" to "Fan and amounts assume a discard win under the current rules; self-draw adds more.",
    "知道了" to "Got it",
    "碰" to "Pong",
    "碰碰和" to "All Pungs",
    "碰碰胡" to "All Pungs",
    "碰碰胡且全是 2/5/8" to "All Pungs, all 2/5/8",
    "碰碰胡（1 番）" to "All Pungs (1 fan)",
    "碰碰胡，且所有牌都是 2 / 5 / 8。" to "All Pungs where every tile is a 2, 5, or 8.",
    "箭刻" to "Dragon Pung",
    "组合龙" to "Knitted Straight",
    "结算方式" to "Settlement",
    "结算（单家）" to "Settlement (per opponent)",
    "绝张" to "Last Tile",
    "绝张（+1 番）" to "Last Tile (+1 fan)",
    "绿一色" to "All Green",
    "缺一门" to "One Voided Suit",
    "缺少输出" to "missing output",
    "老少副" to "Two Terminal Chows",
    "胡「%@」" to "Win on 「%@」",
    "胡的那张，自己已有 3 张（手里 / 碰），胡它=第 4 张" to "You already hold 3 of the winning tile (in hand / pong) and win the 4th",
    "胡第一张打出的牌" to "Win on the first discard",
    "自动排序" to "Auto-sort",
    "自己摸到和牌的那张牌。" to "You drew the winning tile yourself.",
    "自己摸到胡的那张牌。" to "You draw the winning tile yourself.",
    "自摸" to "Self-draw",
    "自摸 · 三家各付" to "Self-draw · each of 3 pays",
    "自摸侧" to "self-draw side",
    "自摸和" to "Self-drawn",
    "自摸时" to "On self-draw:",
    "自摸牌墙上最后一张牌和牌。" to "Self-drawing the very last tile of the wall.",
    "自摸（三家各付）" to "Self-draw (each of 3 pays)",
    "花牌" to "Flower Tiles",
    "花龙" to "Mixed Straight",
    "西" to "West",
    "规则细则" to "House Rules",
    "规则设置" to "Rule Settings",
    "计法" to "Scoring Method",
    "计钱" to "Money",
    "识别到 %lld 张牌（应为 13 或 14）。" to "Recognised %lld tiles (should be 13 or 14). ",
    "识别到 %lld 张牌（应为 13 或 14），可能混入了桌上其他人的牌，或有漏识别。已回填识别结果，请核对后再分析。" to "Recognized %lld tiles (13 or 14 expected). Other players' tiles may have slipped in, or some were missed. The result has been filled in — check it, then analyze.",
    "识别到超过 %lld 张牌，已保留前 %lld 张。" to "More than %1\$lld tiles recognized; kept the first %2\$lld.",
    "识别到超过 %lld 张牌，已保留前 %lld 张，请核对后再计算。" to "Recognized more than %lld tiles; kept the first %lld. Please double-check before calculating.",
    "识别整张照片" to "Recognize whole photo",
    "识别选中区域" to "Recognize selection",
    "请先选择手牌。" to "Please select hand tiles first.",
    "调整选区" to "Adjust selection",
    "豪华七小对" to "Deluxe Seven Pairs",
    "豪华七小对（每龙 +1 番）" to "Deluxe Seven Pairs (+1 fan per dragon)",
    "豪华七小对（豪七）" to "Deluxe Seven Pairs",
    "边张" to "Edge Wait",
    "边张 / 坎张 / 单钓将就高算" to "Take the best reading for edge, closed and pair waits",
    "这副牌的牌型能和，但手牌加副露还不满 14 张——缺的面子按「能凑成」处理，所以不算番分。补齐 14 张后才会给出番分与起和判定。" to "This shape can win, but hand plus melds is still short of 14 tiles — the missing sets are assumed completable, so no points are scored. Fill it to 14 tiles to get points and the 8-point check.",
    "进张 %lld 张" to "%lld tiles improve",
    "进张 %lld 张 · %lld 门" to "%lld tiles · %lld kinds",
    "连七对" to "Seven Shifted Pairs",
    "连六" to "Short Straight",
    "选入手牌" to "Select hand tiles",
    "选牌后点「分析手牌」：手牌 3n+1 张算听牌/向听，3n+2 张给打牌建议；已吃、已碰、已杠的牌用底部「吃 / 碰 / 明杠 / 暗杠」加到桌上。国标起和 8 分，花牌另计不进起和分。" to "Pick tiles, then tap Analyse: 3n+1 tiles gives waits / shanten, 3n+2 gives discard advice. Add chows, pongs and kongs with the keypad's Chow / Pong / Exposed kong / Concealed kong tabs. MCR needs 8 points to win; flowers score separately and do not count toward the 8.",
    "选牌后点「分析手牌」：手牌 3n+1 张算听牌/向听，3n+2 张给打牌建议；已碰、已杠的牌用底部「碰 / 明杠 / 暗杠」加到桌上。" to "After picking tiles, tap Analyze: a 3n+1 hand gives tenpai/shanten, a 3n+2 hand gives discard advice. Add ponged/konged tiles to the table with Pong / Exposed Kong / Concealed Kong below.",
    "重拍" to "Retake",
    "金钩钓" to "Golden Hook",
    "金钩钓 + 4 杠（含 4 根）" to "Golden Hook + 4 kongs (incl. 4 roots)",
    "金钩钓且四副都是杠（4 个杠 = 4 根）。" to "Golden Hook where all four melds are kongs (4 kongs = 4 roots).",
    "金额 = 底分 × 2^番数（封顶截断），为单家输赢：点炮由放炮者付，自摸三家各付。" to "Amount = base × 2^fan (capped), per opponent: on a discard win the discarder pays; on self-draw each of the three pays.",
    "金额为单家：点炮时放炮那家付这个数。点牌可看番型明细。" to "Amounts are per opponent: on a discard win the discarder pays this. Tap a tile for the fan breakdown.",
    "金额为单家：自摸后三家各付这个数。点牌可看番型明细。" to "Amounts are per opponent: on self-draw each of the other three pays this. Tap a tile for the fan breakdown.",
    "门前清" to "Concealed Hand",
    "门前清且自摸。" to "A fully concealed hand won by self-draw.",
    "门清" to "Concealed Hand",
    "门清 = 没有碰、没有明杠（暗杠可），点炮/自摸都算。断幺九 = 整副牌完全没有 1 和 9。七小对关闭后，七对牌型不计基础 2 番；豪华关闭则龙七对按平七小对计。将对 = 碰碰胡且全是 2/5/8（关闭时按普通碰碰胡/七小对计）。金钩钓已含碰碰胡，不叠加。" to "Concealed Hand = no pong and no exposed kong (concealed kong OK); counts on both discard and self-draw. All Simples = no 1s or 9s anywhere. With Seven Pairs off, seven-pair hands score no base 2 fan; with Deluxe off, a dragon seven pairs scores as plain Seven Pairs. Jiang Pungs = All Pungs all 2/5/8 (off → scored as ordinary All Pungs / Seven Pairs). Golden Hook already includes All Pungs and does not stack.",
    "门清一色 1112345678999 再加同花色任意一张。" to "Concealed 1112345678999 in one suit plus any extra tile of that suit.",
    "门清（+1 番）" to "Concealed Hand (+1 fan)",
    "门风" to "Seat wind",
    "门风刻" to "Seat Wind",
    "闲家胡第一圈打出的第一张牌。" to "A non-dealer wins on the first tile discarded in the first round.",
    "附加番" to "Additional Fans",
    "（含暗杠——只露一张、靠猜，尤其请核对）" to " (incl. a guessed concealed kong — only one tile shown; please double-check)",
)
