//
//  EnStrings.kt
//  由 iOS Localizable.xcstrings 生成的英文对照表（key = 中文源文案，与 iOS 完全同源）。
//  重新生成：见 android 仓库 README。请勿手改——改 iOS xcstrings 后重新生成。
//

package com.feiyu.majiang.core

val EN_STRINGS: Map<String, String> = mapOf(
    "%lld / 4 组" to "%lld / 4 sets",
    "%lld 番" to "%lld fan",
    "%lld 番·封顶 %lld" to "%lld fan · cap %lld",
    "%lld 种" to "%lld options",
    "+%lld 底" to "+%lld base",
    "+%lld 番" to "+%lld fan",
    "+1 底" to "+1 base",
    "+1 番" to "+1 fan",
    "+4 番" to "+4 fan",
    "0 番" to "0 fan",
    "1 番" to "1 fan",
    "2 番" to "2 fan",
    "3 番" to "3 fan",
    "3 番（8 倍）" to "3 fan (8×)",
    "4 张同牌：杠 / 手握 4 张 / 碰 + 手里第 4 张" to "Four identical tiles: a kong, four in hand, or a pong + the 4th in hand",
    "4 番" to "4 fan",
    "4 番（16 倍）" to "4 fan (16×)",
    "5 番" to "5 fan",
    "5 番（32 倍）" to "5 fan (32×)",
    "AI 正在识别牌面…" to "Recognizing tiles…",
    "「%@」在手牌和副露里已用满 4 张。" to "All 4 of 「%@」are already used across hand and melds.",
    "「%@」总数会超过 4 张，无法%@。" to "That would exceed 4 of 「%@」— can't %@.",
    "七小对" to "Seven Pairs",
    "七小对且全是 2/5/8" to "Seven Pairs, all 2/5/8",
    "七小对（2 番）" to "Seven Pairs (2 fan)",
    "三豪华七小对" to "Triple Deluxe Seven Pairs",
    "不封顶" to "No cap",
    "不计" to "Not counted",
    "从相册选择" to "Choose from Library",
    "元" to "unit",
    "兜底" to "fallback",
    "共 %lld 门" to "%lld waits",
    "关闭" to "Off",
    "凑齐 4 张同牌：杠 / 手握 4 张 / 碰 + 手里第 4 张" to "Four identical tiles: a kong, four in hand, or a pong + the 4th in hand",
    "分析手牌" to "Analyze",
    "分析结果" to "Result",
    "切换语言" to "Switch language",
    "删除 %@%@" to "Remove %@%@",
    "剩%lld" to "%lld left",
    "加入到" to "Add to",
    "加底（+1 底分）" to "Add base (+1 base)",
    "加番（+1 番）" to "Add fan (+1 fan)",
    "十八罗汉" to "Eighteen Arhats",
    "双豪华七小对" to "Double Deluxe Seven Pairs",
    "取消" to "Cancel",
    "只有杠才算根" to "Only kongs count as root",
    "只有杠：明杠 / 暗杠" to "Kongs only: exposed / concealed kong",
    "向听 %lld" to "%lld away",
    "听牌" to "Tenpai",
    "听牌计算器" to "Tenpai Calculator",
    "听牌（空听）" to "Tenpai (Dead Wait)",
    "在底部选择花色与点数加入；点击已选牌可删除" to "Add tiles from the keyboard below; tap a tile to remove it",
    "地胡" to "Earthly Hand",
    "场景番（胡牌时勾选）" to "Situational Fans (check at win)",
    "基础牌型（自动识别，可叠加）" to "Base Patterns (auto-detected, stackable)",
    "天胡" to "Heavenly Hand",
    "完成" to "Done",
    "封顶" to "Cap",
    "将七对" to "Jiang Seven Pairs",
    "将对" to "Jiang Pungs",
    "将对 / 将七对（3 / 4 番）" to "Jiang Pungs / Jiang Seven Pairs (3 / 4 fan)",
    "尚未选牌" to "No tiles yet",
    "已关闭" to "Off",
    "已含碰碰胡，不叠加" to "Includes All Pungs; not stacked",
    "已听牌，但可胡的牌都已在手中（4 张用尽），无法再胡——空听。" to "You're ready, but every winning tile is already in your hand (all 4 used) — a dead wait, no win possible.",
    "已和！" to "Won!",
    "已碰、已杠的牌放这里：底部切到「碰 / 明杠 / 暗杠」后点牌加入。" to "Melded (ponged/konged) tiles go here: switch the bottom keyboard to Pong / Exposed Kong / Concealed Kong, then tap a tile.",
    "已自动分组：%lld 张手牌 + %lld 副露%@。请核对「桌上的牌」无误后，点『分析手牌』。" to "Auto-grouped: %lld hand tiles + %lld melds%@. Check the Table Tiles, then tap Analyze.",
    "已识别 %lld 张，请核对后再分析。" to "Recognized %lld tiles; please double-check before analyzing.",
    "常见组合（自动叠出，不单列）" to "Common Combos (auto-stacked, not listed separately)",
    "平胡" to "Basic Win",
    "庄家起手胡" to "Dealer wins on the opening hand",
    "底分" to "Base stake",
    "当前副露 %lld 组，手牌需为 %@ 张（听牌）或再多 1 张（打牌建议）。当前手牌 %lld 张。" to "With %lld melds, the hand needs %@ tiles (tenpai) or one more (discard advice). Currently %lld tiles.",
    "恢复默认规则" to "Restore Default Rules",
    "手牌" to "Hand",
    "手牌与副露合计含万、筒、条三门花色（花猪）。四川麻将需缺一门，请打缺其中一门。" to "Hand and melds together use all three suits — Characters, Dots, and Bamboo (a \"flower pig\"). Sichuan mahjong requires dropping one suit.",
    "手牌太多，放不下这组副露——先删几张手牌（碰/杠会占掉 3 张名额）。" to "Too many hand tiles to add this meld — remove some first (a pong/kong takes 3 slots).",
    "手里的牌" to "Hand Tiles",
    "打" to "Discard",
    "打牌建议" to "Discard Suggestions",
    "抢杠胡" to "Robbing the Kong",
    "拍照" to "Take Photo",
    "拍照识别手牌" to "Recognize from Photo",
    "拖动框选 · 可旋转" to "Drag to crop · rotatable",
    "换一张" to "Change",
    "提示" to "Notice",
    "撤销" to "Undo",
    "整副牌完全没有 1 和 9" to "No 1s or 9s anywhere in the hand",
    "断幺九" to "All Simples",
    "断幺九（+1 番）" to "All Simples (+1 fan)",
    "旋转" to "Rotate",
    "无有效进张（受缺一门所限）。" to "No useful draws (limited by the missing-suit rule).",
    "无法读取所选图片，请换一张试试。" to "Could not read the image; please try another.",
    "明杠" to "Exposed Kong",
    "暗杠" to "Concealed Kong",
    "最多 4 组副露。" to "At most 4 melds.",
    "未找到本地识别模型文件。" to "On-device recognition model not found.",
    "未能从图片中识别到麻将牌，请确保牌面清晰、正对镜头、光线充足。" to "No tiles recognized. Make sure the tiles are clear, facing the camera, and well lit.",
    "本地识别失败：%@" to "On-device recognition failed: %@",
    "杠上开花" to "After-Kong Bloom",
    "杠上开花（+1 番）" to "After-Kong Bloom (+1 fan)",
    "杠上炮" to "After-Kong Discard",
    "根" to "Root",
    "根 = 4 张同牌。默认「碰 + 手里第 4 张」「手握 4 张」也算根；开启「只有杠才算根」后仅明杠/暗杠算。加底/关闭时，杠只按刮风下雨即时结算，不再翻倍进胡牌金额。" to "Root = four identical tiles. By default a pong + 4th tile and four-in-hand also count; turn on “Only kongs count as root” to count exposed/concealed kongs only. On Add-base/Off, kongs settle instantly (wind/rain) and no longer double the win amount.",
    "根 = 凑齐 4 张同牌（杠 / 手握 4 张 / 碰 + 第 4 张）。加底/关闭时，杠只按刮风下雨即时结算，不再翻倍进胡牌金额。" to "Root = four identical tiles (a kong, four in hand, or a pong + 4th tile). On Add-base/Off, kongs settle instantly (wind/rain) and no longer double the win amount.",
    "桌上的牌（碰 / 杠）" to "Table Tiles (Pong / Kong)",
    "每个 +1 底" to "+1 base each",
    "每个 +1 番" to "+1 fan each",
    "每多一龙再 +1：双豪华 4 番、三豪华 5 番" to "+1 per extra dragon: Double Deluxe 4 fan, Triple Deluxe 5 fan",
    "没有碰、没有明杠（暗杠可），点炮/自摸都算" to "No pong, no exposed kong (concealed kong OK); counts on discard and self-draw",
    "海底捞月" to "Last-Tile Draw",
    "清一色" to "Pure Suit",
    "清一色（2 番）" to "Pure Suit (2 fan)",
    "清七对" to "Pure Seven Pairs",
    "清对（清一色 + 碰碰胡）" to "Pure Pungs (Pure Suit + All Pungs)",
    "清空全部" to "Clear all",
    "清豪七" to "Pure Deluxe Seven Pairs",
    "清金钩钓" to "Pure Golden Hook",
    "清除框选" to "Clear selection",
    "点炮" to "Discard",
    "点炮 · 放炮者付" to "Discard · discarder pays",
    "点炮侧" to "discard side",
    "点炮时" to "On discard:",
    "点炮（放炮者付）" to "Discard (discarder pays)",
    "点选加入" to "Tap to add",
    "番型" to "Fans",
    "番型一览" to "Fan Reference",
    "番型开关" to "Fan Toggles",
    "番型明细" to "Fan Breakdown",
    "碰" to "Pong",
    "碰碰胡" to "All Pungs",
    "碰碰胡且全是 2/5/8" to "All Pungs, all 2/5/8",
    "碰碰胡（1 番）" to "All Pungs (1 fan)",
    "结算方式" to "Settlement",
    "结算（单家）" to "Settlement (per opponent)",
    "绝张" to "Last Tile",
    "绝张（+1 番）" to "Last Tile (+1 fan)",
    "缺少输出" to "missing output",
    "胡「%@」" to "Win on 「%@」",
    "胡的那张，自己已有 3 张（手里 / 碰），胡它=第 4 张" to "You already hold 3 of the winning tile (in hand / pong) and win the 4th",
    "胡第一张打出的牌" to "Win on the first discard",
    "自动排序" to "Auto-sort",
    "自摸" to "Self-draw",
    "自摸 · 三家各付" to "Self-draw · each of 3 pays",
    "自摸侧" to "self-draw side",
    "自摸时" to "On self-draw:",
    "自摸（三家各付）" to "Self-draw (each of 3 pays)",
    "规则设置" to "Rule Settings",
    "计法" to "Scoring Method",
    "计钱" to "Money",
    "识别到超过 %lld 张牌，已保留前 %lld 张，请核对后再计算。" to "Recognized more than %lld tiles; kept the first %lld. Please double-check before calculating.",
    "识别整张照片" to "Recognize whole photo",
    "识别选中区域" to "Recognize selection",
    "请先选择手牌。" to "Please select hand tiles first.",
    "调整选区" to "Adjust selection",
    "豪华七小对" to "Deluxe Seven Pairs",
    "豪华七小对（每龙 +1 番）" to "Deluxe Seven Pairs (+1 fan per dragon)",
    "豪华七小对（豪七）" to "Deluxe Seven Pairs",
    "进张 %lld 张" to "%lld tiles improve",
    "进张 %lld 张 · %lld 门" to "%lld tiles · %lld kinds",
    "选择图片来源" to "Choose Image Source",
    "选牌后点「分析手牌」：手牌 3n+1 张算听牌/向听，3n+2 张给打牌建议；已碰、已杠的牌用底部「碰 / 明杠 / 暗杠」加到桌上。" to "After picking tiles, tap Analyze: a 3n+1 hand gives tenpai/shanten, a 3n+2 hand gives discard advice. Add ponged/konged tiles to the table with Pong / Exposed Kong / Concealed Kong below.",
    "重拍" to "Retake",
    "金钩钓" to "Golden Hook",
    "金钩钓 + 4 杠（含 4 根）" to "Golden Hook + 4 kongs (incl. 4 roots)",
    "金额 = 底分 × 2^番数（封顶截断），为单家输赢：点炮由放炮者付，自摸三家各付。" to "Amount = base × 2^fan (capped), per opponent: on a discard win the discarder pays; on self-draw each of the three pays.",
    "金额为单家：点炮时放炮那家付这个数。点牌可看番型明细。" to "Amounts are per opponent: on a discard win the discarder pays this. Tap a tile for the fan breakdown.",
    "金额为单家：自摸后三家各付这个数。点牌可看番型明细。" to "Amounts are per opponent: on self-draw each of the other three pays this. Tap a tile for the fan breakdown.",
    "门清" to "Concealed Hand",
    "门清 = 没有碰、没有明杠（暗杠可），点炮/自摸都算。断幺九 = 整副牌完全没有 1 和 9。七小对关闭后，七对牌型不计基础 2 番；豪华关闭则龙七对按平七小对计。将对 = 碰碰胡且全是 2/5/8（关闭时按普通碰碰胡/七小对计）。金钩钓已含碰碰胡，不叠加。" to "Concealed Hand = no pong and no exposed kong (concealed kong OK); counts on both discard and self-draw. All Simples = no 1s or 9s anywhere. With Seven Pairs off, seven-pair hands score no base 2 fan; with Deluxe off, a dragon seven pairs scores as plain Seven Pairs. Jiang Pungs = All Pungs all 2/5/8 (off → scored as ordinary All Pungs / Seven Pairs). Golden Hook already includes All Pungs and does not stack.",
    "门清（+1 番）" to "Concealed Hand (+1 fan)",
    "附加番" to "Additional Fans",
    "（含暗杠——只露一张、靠猜，尤其请核对）" to " (incl. a guessed concealed kong — only one tile shown; please double-check)",
)
